### ISSUE TITLE
Find songs by album is possible

### ISSUE THREAD

**Issue by mrzmyr** [scf4/lyricist#12]
It is actually possible to search for albums by title by using `/album` on the `/search` url like this:

`https://api.genius.com/search/album?access_token=ACCESS_TOKEN&q=Lanterns`

So, probably it's possible to implement a function like `searchAlbum(title)` like your internal `search(title)` function.

**Comment by vitaliikravets** [comment]
Probably not anymore. I am getting:
`{"meta":{"status":403,"message":"Action forbidden for current scope"}}`
