### ISSUE TITLE
Valid Access Token yet Describe is not Defined 

### ISSUE THREAD

**Issue by jgrxl** [scf4/lyricist#14]
`const Lyricist = require('./');
require('dotenv').config();

describe('Lyricist', () => {
  const lyricist = new Lyricist("MYTOKEN");
`

At temping to use my access token to use lyricist yet says describe is not defined. Current version of nodejs.

**Comment by scf4** [comment]
If you’re just trying to *use* the package (not contribute to its development), then the index.test.js file isn’t relevant to your needs. 

That file isn’t an example of usage, it’s for the test suite to ensure that everything works (and that we don’t break anything) while changing/adding things to the package. 

See the README.md for how to use the package. It’s much more straightforward than what you’re trying to do!

Just require "lyricist" and then create a new instance with your API key:

const Lyricist = require('lyricist');
const lyricist = new Lyricist("MYTOKEN");
