### ISSUE TITLE
Please add support for optional genius api host address

### ISSUE THREAD

**Issue by vitaliikravets** [scf4/lyricist#16]
I would like to use this library from browser.
In order to fight the CORS , improve performance and lower the load on actual API, I am setting up a CDN that will have the same domain name as my website but will redirect all calls to genius.com.

**Comment by scf4** [comment]
This would be a super simple PR 🙂 The API address used by every function is defined in just one place

**Comment by scf4** [comment]
Just noticed you said browser. Don't use this on a public-facing website. You would be exposing your API key.
