### ISSUE TITLE
Support text_format option

### ISSUE THREAD

**Issue by jch254** [scf4/lyricist#7]
Any chance of the text_format option? 

From Genius Docs:

Many API requests accept a text_format query parameter that can be used to specify how text content is formatted. The value for the parameter must be one or more of plain, html, and dom. The value returned will be an object with key-value pairs of formats and results:

plain is just plain text, no markup
html is a string of unescaped HTML suitable for rendering by a browser
dom is a nested object representing and HTML DOM hierarchy that can be used to programmatically present structured content

Cheers for the great work with Lyricist! Simple and easy to use

**Comment by Scriptim** [comment]
I created a [pull request](https://github.com/scf4/lyricist/pull/8), but some checks fail. I guess, 'scf4' has to fix this manually.

**Comment by scf4** [comment]
Merged and pushed to NPM. Thanks guys.

**Comment by jch254** [comment]
Cheers @scf4! Champion
